[package]
name = "cryptography_with_rust"
version = "0.1.0"
authors = ["Zhang Tianwei <zhangtianwei1015@gmail.com>"]
edition = "2021"

[[bin]]
name = "hasher"
path = "examples/file_hasher.rs"
doc = false

[dependencies]

[dev-dependencies]
hex = "0.4.3"